# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: 'CI'
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build container
        run: docker compose build
      - name: Boot containers
        run: docker-compose up -d app chrome_server
      - name: Run tests
        run: docker compose exec -T app bin/rails test
      - name: Run system tests
        run: docker compose exec -T app bin/rails app:test:system
